version: '3.5'

services:
  app:
    image: bauk/spring-petclinic:${VERSION}
    build:
      context: .
      args:
        VERSION: ${VERSION}
    ports:
      - "8082:8080"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    #volumes:
      #- "./conf.d:/etc/mysql/conf.d:ro"
